---
title: "R Shiny App East Africa Covid Cases"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---




```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
library(plyr)
library(dplyr)
library(shinyWidgets)
library(RColorBrewer)
library(plotly)
library(leaflet)
library(readxl)
library(shinythemes)
```


```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared
# by all users of the dashboard

#Load the data we dowonloaded before. Change this according to where you stored your data.

mydata<- read.csv( "C:\\Users\\Dorcas\\Documents\\GitHub\\R-Ladies-Siny-App-Class\\Data\\covid_data.csv")

#Filter for East African Countries

ea_data<-filter(mydata, country %in% c('Kenya', 'Uganda', "Tanzania", "Rwanda", "Burundi"))

#Exploring the data
head(ea_data)
tail(ea_data)


```



Column {.sidebar}
-----------------------------------------------------------------------

This dashboard allows us to explore covid cases in East Africa. Please use the buttons below to interact with the dashboard

```{r}

 selectInput("CountryInput", label = 
                        "Country:",
                        choices = c("Kenya", 'Uganda', "Tanzania", "Rwanda", "Burundi"), selected = "Kenya")

```

Column 
-----------------------------------------------------------------------

### The actual graph (using the global data we created)

```{r}

renderPlot({
        
        filtered <-ea_data %>% filter(
            country== input$CountryInput
                )
    
        ggplot(filtered, aes(x=date, y=deaths)) + geom_line() +geom_point() + labs(y= "Deaths")
        
        }
        
    )

```

