---
title: "R Ladies Nairobi Shiny Exercise guide"
author: "Dorcas K"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As good coding habit, always write down at the top of the script detais that can help someone else using the code.


So the first few lines (commented), add the details of this exercise. Author name, Date (exact or month), and purpose of the script.

```{r details of script}
#Dorcas Kareithi
#December 2020
#Task: Create a Shiny App to explore the reach of Nairobi R ladies in twitter
```


After that, we load all the libraries we may need

```{r loading libraries}
library(shiny)
library(ggplot2)
library(plyr)
library(dplyr)
library(shinyWidgets)
library(RColorBrewer)
library(plotly)
library(leaflet)
library(readxl)
library(shinythemes)

#We may need to install one more library (changed the dataset last minute when I found out that Twotter is blocked in the country I am currently at and wanted to do a live dashboard)
#Installing the tidy covid 19 package

#Install tidycovid package. Uncomment the line below
#remotes::install_github("joachim-gassen/tidycovid19")

#once done installing, comment back and load the libraries below

library(tidycovid19)
library(tidyverse)

```


```{r data preparation}

#Load the data we dowonloaded before. Change this according to where you stored your data.

mydata<- read.csv( "C:\\Users\\Dorcas\\Documents\\GitHub\\R-Ladies-Siny-App-Class\\Data\\covid_data.csv")

#Filter for East African Countries

ea_data<-filter(mydata, country %in% c('Kenya', 'Uganda', "Tanzania", "Rwanda", "Burundi"))

#Exploring the data
head(ea_data)
tail(ea_data)

View(ea_data)

```

```{r ui part of the script}
# Define UI for application that draws a histogram
ui <- fluidPage(
    titlePanel("Kenya COVID Cases Data"),
    
    
    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            selectInput("CountryInput",
                        "Country:",
                        choices = c("Kenya", 'Uganda', "Tanzania", "Rwanda", "Burundi")),
            
        ),
        
        # Show a plot of the generated distribution
        mainPanel(
            
            plotOutput("countries_plot"),
            br(), br(),
            
            
        )
    )
)
```

```{r server side of the code}
# Define server logic required to draw a histogram
server <- function(input, output) {
    
    output$countries_plot <-renderPlot({
        
        filtered <-ea_data %>% filter(
            country== input$CountryInput
                )
    
        ggplot(filtered, aes(x=date, y=deaths)) + geom_line() +geom_point() + labs(y= "Deaths")
        
        }
        
    )

}
```


```{r combining both}
# Run the application 
shinyApp(ui = ui, server = server)
```


```{r assignment}
#Assignment:
#Try adding another dropdown or radio button to enable the user select the se=pecific case they want to display ie whether deaths, cases or recoveries
```

