---
title: "R Ladies Flex Dahsboaard Exercise guide"
author: "Dorcas K"
date: "12/15/2020"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As good coding habit, always write down at the top of the script detais that can help someone else using the code.


So the first few lines (commented), add the details of this exercise. Author name, Date (exact or month), and purpose of the script.

```{r details of script}
#Dorcas Kareithi
#December 2020
#Task: Create a Flex Dashboard to explore the reach of Nairobi R ladies in twitter
```

```{r creating the flex dashboard file}
#Go to File
#Select New File
#Select R markdown
#On the left tab, Select from template
#Select Flex Dashboard
```


```{r Editing flex dashboard file to produce a shiny dashboard}
#Add runtime: shiny to the options declared at the top of the document (bwlow vertical_layout: fill)
#Add the {.sidebar} attribute to the first column of the dashboard to make it a host for Shiny input controls (

```



After that, we load all the libraries we may need

```{r loading libraries}
library(shiny)
library(ggplot2)
library(plyr)
library(dplyr)
library(shinyWidgets)
library(RColorBrewer)
library(plotly)
library(leaflet)
library(readxl)
library(shinythemes)

#We may need to install one more library (changed the dataset last minute when I found out that Twotter is blocked in the country I am currently at and wanted to do a live dashboard)
#Installing the tidy covid 19 package

#Install tidycovid package. Uncomment the line below
#remotes::install_github("joachim-gassen/tidycovid19")

#once done installing, comment back and load the libraries below

library(tidycovid19)
library(tidyverse)

```



```{r preparing the data }
# load data in 'global' chunk so it can be shared
# by all users of the dashboard

#Load the data we dowonloaded before. Change this according to where you stored your data.

mydata<- read.csv( "C:\\Users\\Dorcas\\Documents\\GitHub\\R-Ladies-Siny-App-Class\\Data\\covid_data.csv")

#Filter for East African Countries

ea_data<-filter(mydata, country %in% c('Kenya', 'Uganda', "Tanzania", "Rwanda", "Burundi"))

#Exploring the data
head(ea_data)
tail(ea_data)


```

```{r Editing the column sections}
#In the first section, make it a side bar. 
#We will then add a select input option, allowing the user to change between options selected
#Paste the following there 

#Column {.sidebar}
#-----------------------------------------------------------------------

#This dashboard allows us to explore covid cases in East Africa. Please use the buttons below to interact with the dashboard

 selectInput("CountryInput", label = 
                        "Country:",
                        choices = c("Kenya", 'Uganda', "Tanzania", "Rwanda", "Burundi"), selected = "Kenya")

```

```{r Editing the area that displays the chart}
#required to draw a graph
#Paste this:

#Column 
#-----------------------------------------------------------------------

### The actual graph


renderPlot({
        
        filtered <-ea_data %>% filter(
            country== input$CountryInput
                )
    
        ggplot(filtered, aes(x=date, y=deaths)) + geom_line() +geom_point() + labs(y= "Deaths")
        
        }
        
    )

```

```{r assignment}
#Assignment:
#Try adding another dropdown or radio button to enable the user select the se=pecific case they want to display ie whether deaths, cases or recoveries
```

